### ISSUE TITLE
CompatibilityMode not working

### ISSUE THREAD

**Issue by dineshkumarwin** [Gavin-Paolucci-Kleinow/ie-truth#3]
I tested my site using IE 11 in Compatibility Mode (Edge). the Compatibility Mode returns false

**Comment by Gabby-Paolucci** [comment]
Is your site publicly accessible so that I can troubleshoot?

**Comment by dineshkumarwin** [comment]
Sorry @Gavin-Paolucci-Kleinow  my mistake, I forgot to check document mode

**Comment by Gabby-Paolucci** [comment]
No worries. Glad you got it working.
